apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v3s0jpa2i-java-quarkus
  janus-idp.io/tekton: v3s0jpa2i-java-quarkus
  backstage.io/kubernetes-id: v3s0jpa2i-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v3s0jpa2i-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
