apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: v3s0jpa2i-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a17b9ddf2a.4wjs.p3.openshiftapps.com/rhtap/rhtap-qe:c7257ab857923a9b6847d4f091cb58f73654fafc@sha256:10ada59245b7c4c09bae8132edfb103a4083b46ccf51b4e78b470e943653d45d
        name: container-image  
